name: CI
run-name: "${{ github.event_name == 'workflow_dispatch' && format('CI: {0}', github.ref_name) || '' }}"

on:
  push: ~

env:
  PYTHON_VERSION: "3.12"

jobs:
  linting:
    name: Run linting
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        id: python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          check-latest: true
      - name: Create Python virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          python --version
          pip install -r requirements_dev.txt
      - name: Install pre-commit dependencies
        run: |
          . venv/bin/activate
          pre-commit install-hooks

      - name: Run codespell
        run: |
          . venv/bin/activate
          pre-commit run --hook-stage manual codespell --all-files --show-diff-on-failure

      - name: Run check-toml
        run: |
          . venv/bin/activate
          pre-commit run --hook-stage manual check-toml --all-files --show-diff-on-failure

      - name: Run check-yaml
        run: |
          . venv/bin/activate
          pre-commit run --hook-stage manual check-yaml --all-files --show-diff-on-failure

      - name: Run shellcheck
        run: |
          . venv/bin/activate
          pre-commit run --hook-stage manual shellcheck --all-files --show-diff-on-failure

      - name: Python Lint
        id: python-lint
        run: |
          . venv/bin/activate
          pre-commit run --hook-stage manual isort --all-files --show-diff-on-failure
          pre-commit run --hook-stage manual black --all-files --show-diff-on-failure
          pre-commit run --hook-stage manual flake8 --all-files --show-diff-on-failure
          pre-commit run --hook-stage manual bandit --all-files --show-diff-on-failure
          pre-commit run --hook-stage manual pylint --all-files --show-diff-on-failure
